### ISSUE TITLE
No Syntax Highlighting available

### ISSUE THREAD

**Issue by verpixelt** [nathos/sass-textmate-bundle#34]
Hey folks,

today I've started ST2 and noticed the lack of Sass syntax highlighting. I tried to choose it from the menu in the right bottom corner but Sass isn't listed there. I've reinstalled the plugin twice but it is still not working. No reports in the console log.

**Comment by craigcosmo** [comment]
it's not working in st3.

I installed plugin via package control. It's not showing syntax highlight, and auto completion. I Have set view->syntax-> sass. still not work.
