### ISSUE TITLE
ST3: Autocomplete doesn't work as expected?

### ISSUE THREAD

**Issue by altdeveloper** [nathos/sass-textmate-bundle#72]
Hi there,

I have the SASS plugin installed for ST3 and it appears to work but for example if I type bdrz it autocompletes to Border-Radius  but if I type border I get no autocomplete for border-radius

In the css file it works.

Is this configurable in any way so that it works by enter the full word ie.. Border ??

I have the syntax (lower right) set to sass

Thanks

**Comment by nathos** [comment]
Hi @altdeveloper,

This is a known issue with the current package. It still has Zen Coding (now known as Emmet) shortcut expansions built in to the syntax file, and some expansions from the standard CSS file don't work as expected. This is a remnant from the old TextMate (and pre-SCSS) days.

I don't have a simple workaround right now, as the real solution involves a complete rewrite of the syntax definitions for both SCSS and Sass (indented) syntaxes.

If you're primarily using SCSS syntax, you can give the SCSS Sublime Text package a try. In the meantime, I apologize for the inconvenience. I haven't really had any time to work on this package in a while, though I'd love to at least start to organize a plan to update everything (keep an eye on https://github.com/nathos/sass-textmate-bundle/milestones )

**Comment by altdeveloper** [comment]
Hey @nathos , thanks. Your suggestion of the SCSS Sublime Text package, works a treat. I am only interested in the scss syntax.

Thanks!
