### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by paynoattn** [nathos/sass-textmate-bundle#75]
I'm trying to follow your installation instructions and I'm having problems. First of all when I enter the osascript command into terminal I get back a "syntax error: A identifier can’t go after this identifier. (-2740)" message.

Also, when I go to the command pallette Install Packages is not listed in Sublime text v3 (build 3065).

**Comment by nathos** [comment]
Hi @paynoattn,

For Sublime Text, you'll want to install with [Sublime Package Control](https://packagecontrol.io). (the first set of instructions are for TextMate)

Follow the [install instructions](https://packagecontrol.io/installation), then you can use the "Install Package" command in the Sublime command palette.

**Comment by tangorri** [comment]
I can't see either the package listed

**Comment by nathos** [comment]
@tangorri Are you not seeing the package listed inside Sublime? or is there another problem you're running into?

https://packagecontrol.io/packages/Sass

**Comment by tangorri** [comment]
@nathos I mean I cant find the package from sublime.
See 
![sans titre](https://cloud.githubusercontent.com/assets/2960420/7198808/eb105e36-e4ef-11e4-9615-7945ac94008a.png)

**Comment by nathos** [comment]
@tangorri Can you provide some details on your platform? (OS, OS version, Sublime Text version)

A clean Sublime Text 3 w/ Package Control on OS X displays this:
![screen shot 2015-04-20 at 9 52 22 am](https://cloud.githubusercontent.com/assets/4215/7231415/29e02a60-e743-11e4-8830-c80231afde38.png)

**Comment by tangorri** [comment]
Sure, win8.1 pro, sublime text 3. not fresh install btw I may check next time I install st3
