### ISSUE TITLE
Merge this repo into sublimehq/Packages

### ISSUE THREAD

**Issue by jrappen** [nathos/sass-textmate-bundle#86]
Merge this repo into [sublimehq/Packages](http://github.com/sublimehq/Packages).

**Comment by BriceShatzer** [comment]
Unfortunately, I don't believe this will happen per their [recently](https://github.com/sublimehq/Packages/issues/18#issuecomment-113871385) expanded [readme](https://github.com/sublimehq/Packages#pull-requests).
