### ISSUE TITLE
Sublime Text 2: Missing from Package Control 'Sass' listings

### ISSUE THREAD

**Issue by jaegz** [nathos/sass-textmate-bundle#90]
Went to install this package via Package Control Installer on ST2 and it is no longer listed?

When searching 'Sass' here's what's listed:
- SASS Build
- SASS Snippets
- Sass-Director
- SassBeautify
- SassBuilder

**Comment by suicidepills** [comment]
I'm having the same results with ST3.

**Comment by liamcoded** [comment]
Did you guys figure this out? There is no package named just "Sass".

**Comment by jaegz** [comment]
Closing this since I believe this project really isn't maintained anymore (posted this issue over 2 years ago). Also just checked package control and it still doesn't come up.
